"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var wallet_1 = require("./wallet");
Object.defineProperty(exports, "walletProvider", { enumerable: true, get: function () { return wallet_1.default; } });
var transactions_1 = require("./transactions");
Object.defineProperty(exports, "transactionsProvider", { enumerable: true, get: function () { return transactions_1.default; } });
var banks_1 = require("./banks");
Object.defineProperty(exports, "bankProvider", { enumerable: true, get: function () { return banks_1.default; } });
var prices_1 = require("./prices");
Object.defineProperty(exports, "pricesProvider", { enumerable: true, get: function () { return prices_1.default; } });
