const CREATE_WALLET: string = 'WALLETS/CREATE_WALLET';
const GET_WALLET: string = 'WALLETS/GET_WALLET';
const GET_WALLETS: string = 'WALLETS/GET_WALLETS';

const GET_TRANSACTIONS: string = 'TRANSACTIONS/GET_TRANSACTIONS';
const GET_TRANSACTION: string = 'TRANSACTIONS/GET_TRANSACTION';
const CREATE_RECHARGE: string = 'TRANSACTIONS/CREATE_RECHARGE';
const CREATE_PURCHASE: string = 'TRANSACTIONS/CREATE_PURCHASE';
const CREATE_WITHDRAWAL: string = 'TRANSACTIONS/CREATE_WITHDRAWAL';
const CREATE_SEND: string = 'TRANSACTIONS/CREATE_SEND';

export default {
    CREATE_WALLET,
    GET_WALLET,
    GET_WALLETS,
    GET_TRANSACTIONS,
    GET_TRANSACTION,
    CREATE_RECHARGE,
    CREATE_PURCHASE,
    CREATE_WITHDRAWAL,
    CREATE_SEND,
};
