"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CREATE_WALLET = 'WALLETS/CREATE_WALLET';
var GET_WALLET = 'WALLETS/GET_WALLET';
var GET_WALLETS = 'WALLETS/GET_WALLETS';
var GET_TRANSACTIONS = 'TRANSACTIONS/GET_TRANSACTIONS';
var GET_TRANSACTION = 'TRANSACTIONS/GET_TRANSACTION';
var CREATE_RECHARGE = 'TRANSACTIONS/CREATE_RECHARGE';
var CREATE_PURCHASE = 'TRANSACTIONS/CREATE_PURCHASE';
var CREATE_WITHDRAWAL = 'TRANSACTIONS/CREATE_WITHDRAWAL';
var CREATE_SEND = 'TRANSACTIONS/CREATE_SEND';
var CREATE_VITA_SEND = 'TRANSACTIONS/CREATE_VITA_SEND';
var GET_BANKS = 'BANKS/GET_BANKS';
var GET_PRICES = 'PRICES/GET_PRICES';
var GET_VITA_EMAIL = 'VITA_USERS/GET_VITA_EMAIL';
var GET_WITHDRAWAL_RULES = 'TRANSACTIONS/GET_WITHDRAWAL_RULES';
exports.default = {
    CREATE_WALLET: CREATE_WALLET,
    GET_WALLET: GET_WALLET,
    GET_WALLETS: GET_WALLETS,
    GET_TRANSACTIONS: GET_TRANSACTIONS,
    GET_TRANSACTION: GET_TRANSACTION,
    CREATE_RECHARGE: CREATE_RECHARGE,
    CREATE_PURCHASE: CREATE_PURCHASE,
    CREATE_WITHDRAWAL: CREATE_WITHDRAWAL,
    CREATE_SEND: CREATE_SEND,
    CREATE_VITA_SEND: CREATE_VITA_SEND,
    GET_BANKS: GET_BANKS,
    GET_PRICES: GET_PRICES,
    GET_VITA_EMAIL: GET_VITA_EMAIL,
    GET_WITHDRAWAL_RULES: GET_WITHDRAWAL_RULES,
};
