"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CREATE_WALLET = 'WALLETS/CREATE_WALLET';
var GET_WALLET = 'WALLETS/GET_WALLET';
var GET_WALLETS = 'WALLETS/GET_WALLETS';
var GET_TRANSACTIONS = 'TRANSACTIONS/GET_TRANSACTIONS';
var GET_TRANSACTION = 'TRANSACTIONS/GET_TRANSACTION';
var CREATE_RECHARGE = 'TRANSACTIONS/CREATE_RECHARGE';
var CREATE_PURCHASE = 'TRANSACTIONS/CREATE_PURCHASE';
var CREATE_WITHDRAWAL = 'TRANSACTIONS/CREATE_WITHDRAWAL';
var CREATE_SEND = 'TRANSACTIONS/CREATE_SEND';
exports.default = {
    CREATE_WALLET: CREATE_WALLET,
    GET_WALLET: GET_WALLET,
    GET_WALLETS: GET_WALLETS,
    GET_TRANSACTIONS: GET_TRANSACTIONS,
    GET_TRANSACTION: GET_TRANSACTION,
    CREATE_RECHARGE: CREATE_RECHARGE,
    CREATE_PURCHASE: CREATE_PURCHASE,
    CREATE_WITHDRAWAL: CREATE_WITHDRAWAL,
    CREATE_SEND: CREATE_SEND,
};
